# Generated by Django 5.0 on 2023-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
