# Generated by Django 5.0 on 2023-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_created_by_project_super_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=250, verbose_name="description"),
        ),
    ]
