---

version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      CONFIG_PATH: config.yml

  redis:
    init: true
    restart: always
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 1s
      timeout: 10s
      retries: 60
