---

version: '3.8'

services:
  web:
    command: python3 app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: progem
      POSTGRES_PASSWORD: progem
      POSTGRES_DB: progem
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U progem -d progem"]
      interval: 1s
      timeout: 10s
      retries: 60

volumes:
  pgdata:
