# Generated by Django 5.0 on 2023-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='accepted',
            field=models.BooleanField(default=None),
        ),
    ]
