# Generated by Django 5.0 on 2023-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_projectinvitation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
