# Generated by Django 5.0 on 2023-12-11 16:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0004_alter_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.TextField(max_length=50, verbose_name="name")),
                (
                    "description",
                    models.TextField(max_length=250, verbose_name="description"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("finished", models.BooleanField(default=False)),
                ("story_points", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
