# Generated by Django 5.0 on 2023-12-12 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_project_description"),
        ("task", "0002_task_assignee_task_reporter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("DONE", "DONE"),
                    ("IN REVIEW", "IN_REVIEW"),
                    ("PROGRESS", "PROGRESS"),
                    ("TO DO", "TO_DO"),
                    ("NEEDS DISCUSSION", "NEEDS_DISCUSSION"),
                ],
                default="TO DO",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assignee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="project.project",
            ),
        ),
    ]
